plugins:
  autoprefixer: {}
  postcss-cssnext: {}
  postcss-import: {}
  postcss-smart-import: {}
  postcss-assets: {
    loadPaths: ['/app/assets/images/'],
    basePath: 'public',
    cachebuster: true,
  }
